### ISSUE TITLE
URLOutputStream is being imported from an invalid location

### ISSUE THREAD

**Issue by ebailey-vp** [extent-framework/extentreports-cucumber4-adapter#17]
ExtentCucumberAdapter.java is importing UrlOutputStream as follows:

import cucumber.runtime.io.URLOutputStream;

in cucumber-jvm core, this file is actually located at 

cucumber.runtime.formatter.URLOutputStream;

See: https://github.com/cucumber/cucumber-jvm/blob/174c62ee9c03b18920dbe8afdb945f15459b33b0/core/src/main/java/cucumber/runtime/formatter/URLOutputStream.java

**Comment by foursyth** [comment]
This is due to https://github.com/cucumber/cucumber-jvm/commit/eb1a90bd5488421b06acfab4d2b32bf851cdf1db

the adapter is using version:

```<cucumber.version>4.0.1</cucumber.version>```

**Comment by foursyth** [comment]
@anshooarora please upgrade the cucumber dependency

**Comment by grasshopper7** [comment]
The fix for this exists in the git at this [link](https://github.com/extent-framework/extentreports-cucumber4-adapter/blob/master/src/main/java/com/aventstack/extentreports/cucumber/adapter/URLOutputStream.java). This should have been included in the 1.0.7 release but this file was not tagged with 1.0.7 version.
Thus it is missing in the maven repository.

Got the sources and created a jar from master branch locally. Worked with latest cucumber release 4.3.1.

A new release with the proper tag will fix this. Guess @anshooarora can help out. Thanks

**Comment by kathyrollo** [comment]
Hi @foursyth 

Can confirm this issue happens from Cucumber-JVM `4.2.1` and above. ExtentReports is being generated properly using `4.2.0` and below. I am also using the `AbstractTestNGCucumberTests` runner.

Is this an issue with Cucumber-JVM or `extentreports-cucumber4-adapter`?
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running runners.RunCukesTest
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.433 s <<< FAILURE! - in runners.RunCukesTest
[ERROR] setUpClass(runners.RunCukesTest)  Time elapsed: 1.241 s  <<< FAILURE!
java.lang.NoClassDefFoundError: cucumber/runtime/io/URLOutputStream
Caused by: java.lang.ClassNotFoundException: cucumber.runtime.io.URLOutputStream

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   RunCukesTest>AbstractTestNGCucumberTests.setUpClass:16 » NoClassDefFound cucum...
[INFO]
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[ERROR] There are test failures.
```

**Comment by chik145** [comment]
Any update about the issue ?

I Am Using Cucumber Version Is: 4.7.4
Getting "java.lang.NoClassDefFoundError: cucumber/runtime/io/URLOutputStream"

**Comment by anshooarora** [comment]
This is now resolved for Cucumber version `4.7.4`.  Here are the changes: https://github.com/extent-framework/extentreports-cucumber4-adapter/commit/4dba85727a15ddca5d2afacdb64c7a25b36f62a6
